import React from 'react';

export default function About(props){
  return(
    <div>
      <div className='page' id='about' ref={props.refProp}>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
      <div className='page' id='about'>About</div>
    </div>
  ) 
}