import './App.css';
import React from 'react';
import NavBar from './Components/NavBar';
import Home from './Components/Home/Home';

function App() {
  return (
    <div className="App">
      <NavBar/>
      <main>
        <Home />
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vivamus arcu felis bibendum ut tristique et. Amet nulla facilisi morbi tempus iaculis urna id. Adipiscing vitae proin sagittis nisl rhoncus. Amet est placerat in egestas erat imperdiet sed. Nisl pretium fusce id velit ut. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Tellus orci ac auctor augue mauris augue neque gravida. Et magnis dis parturient montes nascetur ridiculus. Tortor condimentum lacinia quis vel. In cursus turpis massa tincidunt. Ac turpis egestas sed tempus urna. Risus commodo viverra maecenas accumsan lacus. Consequat id porta nibh venenatis cras sed. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Diam maecenas sed enim ut sem viverra aliquet. Faucibus in ornare quam viverra orci. Quis eleifend quam adipiscing vitae proin sagittis. At in tellus integer feugiat scelerisque varius morbi.

        At risus viverra adipiscing at. Eu nisl nunc mi ipsum faucibus vitae aliquet. Augue ut lectus arcu bibendum. Pulvinar neque laoreet suspendisse interdum consectetur libero. Varius morbi enim nunc faucibus. Sit amet tellus cras adipiscing enim eu turpis egestas pretium. Nunc scelerisque viverra mauris in aliquam sem. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Adipiscing bibendum est ultricies integer. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Nulla malesuada pellentesque elit eget gravida cum. Et tortor consequat id porta nibh venenatis cras sed. Nibh praesent tristique magna sit amet purus gravida quis blandit. Semper viverra nam libero justo laoreet sit amet. Risus pretium quam vulputate dignissim suspendisse. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur.

        Adipiscing commodo elit at imperdiet dui accumsan sit. Duis at consectetur lorem donec massa. Mattis pellentesque id nibh tortor id aliquet. Senectus et netus et malesuada. Magna fermentum iaculis eu non diam phasellus vestibulum. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Magna sit amet purus gravida quis blandit turpis cursus in. Ac tortor vitae purus faucibus ornare. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Vitae congue eu consequat ac felis. Placerat orci nulla pellentesque dignissim enim. Nec sagittis aliquam malesuada bibendum arcu. Nisi porta lorem mollis aliquam ut porttitor. Nulla malesuada pellentesque elit eget gravida cum sociis.

        Felis eget nunc lobortis mattis aliquam. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Sed odio morbi quis commodo. Viverra suspendisse potenti nullam ac tortor vitae. Nullam non nisi est sit amet facilisis. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Lacinia at quis risus sed vulputate odio ut enim blandit. Facilisis gravida neque convallis a cras. Egestas pretium aenean pharetra magna ac. Posuere morbi leo urna molestie at elementum. Aenean sed adipiscing diam donec adipiscing. Praesent semper feugiat nibh sed pulvinar proin. Viverra vitae congue eu consequat ac felis donec et. Iaculis eu non diam phasellus vestibulum lorem sed.

        Imperdiet sed euismod nisi porta lorem. Sem integer vitae justo eget magna fermentum. Suspendisse in est ante in nibh. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Sed faucibus turpis in eu. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Turpis in eu mi bibendum. Bibendum enim facilisis gravida neque. Vulputate ut pharetra sit amet aliquam id diam. Quis vel eros donec ac odio. Sed vulputate odio ut enim blandit.

        Convallis tellus id interdum velit laoreet. Sit amet tellus cras adipiscing enim eu turpis. Et netus et malesuada fames ac turpis egestas sed. Nulla at volutpat diam ut venenatis. Arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam faucibus purus in. Elementum sagittis vitae et leo. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. Suspendisse interdum consectetur libero id faucibus. Quam id leo in vitae turpis massa. Malesuada fames ac turpis egestas integer eget aliquet nibh. Nunc sed blandit libero volutpat. Quis blandit turpis cursus in hac habitasse platea dictumst quisque. In hac habitasse platea dictumst quisque sagittis purus. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Etiam non quam lacus suspendisse. Pellentesque habitant morbi tristique senectus et. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Tincidunt lobortis feugiat vivamus at augue.

        Neque convallis a cras semper. Egestas diam in arcu cursus euismod. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. In cursus turpis massa tincidunt dui ut ornare. Amet massa vitae tortor condimentum lacinia quis vel eros. Euismod lacinia at quis risus sed. Sed risus ultricies tristique nulla aliquet enim. Ipsum faucibus vitae aliquet nec. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Tellus mauris a diam maecenas sed. Porttitor leo a diam sollicitudin tempor id eu. Fringilla est ullamcorper eget nulla. Pellentesque nec nam aliquam sem et tortor. Vitae ultricies leo integer malesuada nunc. Etiam erat velit scelerisque in. Ac odio tempor orci dapibus ultrices in iaculis nunc sed.

        Rhoncus est pellentesque elit ullamcorper dignissim. Leo integer malesuada nunc vel risus commodo viverra maecenas. Dignissim suspendisse in est ante in nibh mauris cursus. Purus in mollis nunc sed id. Integer feugiat scelerisque varius morbi enim nunc faucibus. Eget est lorem ipsum dolor. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Enim neque volutpat ac tincidunt vitae semper quis lectus. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Sed arcu non odio euismod. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Quisque non tellus orci ac. Augue lacus viverra vitae congue eu consequat ac. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Sit amet justo donec enim diam. Sed nisi lacus sed viverra tellus in hac habitasse. Tincidunt id aliquet risus feugiat in ante. Ultrices mi tempus imperdiet nulla. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique.

        Bibendum neque egestas congue quisque. Lacinia at quis risus sed vulputate. Non tellus orci ac auctor. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Sagittis eu volutpat odio facilisis mauris sit amet. Commodo sed egestas egestas fringilla phasellus. Malesuada fames ac turpis egestas sed tempus urna. Sed pulvinar proin gravida hendrerit. Massa massa ultricies mi quis hendrerit dolor magna eget. Tristique senectus et netus et malesuada fames. Varius duis at consectetur lorem donec massa sapien faucibus et.

        Facilisi morbi tempus iaculis urna id volutpat lacus. Elit at imperdiet dui accumsan sit. Sapien pellentesque habitant morbi tristique senectus et netus et. Libero volutpat sed cras ornare arcu. Felis eget nunc lobortis mattis aliquam faucibus purus in. Semper quis lectus nulla at volutpat diam. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Gravida cum sociis natoque penatibus et magnis. Hendrerit gravida rutrum quisque non tellus. Pulvinar neque laoreet suspendisse interdum consectetur. Pellentesque elit eget gravida cum sociis natoque penatibus. Eget sit amet tellus cras adipiscing enim eu turpis. Velit euismod in pellentesque massa placerat. Mauris in aliquam sem fringilla.
      </main>
    </div>
  );
}

export default App;
